# Generated by Django 5.2.4 on 2025-07-11 03:58

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_status'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        
        User = get_user_model()

        if User.objects.exists():
            return
        
        superuser = User.objects.create_superuser(
            username="admin",
            email="example@email.com",
            password="password",
            last_login=timezone.now()          
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser)
    ]
